#[derive(Copy, Clone)]
pub enum SystemCallArgumentType {
    // Integer can be used to represent int, fd and size_t
    Integer,
    // String can be used to represent *buf
    String,
    // Address can be used to represent *statbuf
    Address,
}

// TODO: these numbers are ridiculously hard to maintain, and should be replaced with constants

pub static TRACE_DESC: [usize; 98] = [
    0, 1, 2, 3, 5, 7, 8, 9, 17, 18, 19, 20, 22, 23, 32, 33, 40, 72, 73, 74, 75, 77, 78, 81, 85, 91,
    93, 187, 190, 193, 196, 199, 213, 217, 221, 232, 233, 240, 242, 243, 244, 245, 253, 254, 255,
    257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 275, 276, 277, 278,
    280, 281, 282, 283, 284, 285, 286, 287, 289, 290, 291, 292, 293, 294, 295, 296, 298, 300, 301,
    303, 304, 306, 308, 313, 316, 319, 320, 321, 322, 323, 326, 327, 328, 332,
];

pub static TRACE_FILE: [usize; 60] = [
    2, 4, 6, 21, 29, 76, 79, 80, 82, 83, 84, 85, 86, 87, 88, 89, 90, 92, 94, 132, 133, 134, 137,
    138, 155, 161, 163, 165, 166, 167, 168, 179, 188, 189, 191, 192, 194, 195, 197, 198, 235, 254,
    257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 280, 301, 303, 316, 332,
];

pub static TRACE_IPC: [usize; 12] = [29, 30, 31, 64, 65, 66, 67, 68, 69, 70, 71, 220];

pub static TRACE_NETWORK: [usize; 19] = [
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 181, 182, 299, 307,
];

pub static TRACE_PROCESS: [usize; 14] = [
    56, 57, 58, 59, 60, 61, 62, 129, 200, 231, 234, 247, 297, 322,
];

pub static TRACE_SIGNAL: [usize; 13] =
    [13, 14, 15, 34, 127, 128, 129, 130, 131, 200, 282, 289, 297];

pub static TRACE_MEMORY: [usize; 23] = [
    9, 10, 11, 12, 25, 26, 27, 28, 30, 149, 150, 151, 152, 206, 207, 216, 237, 238, 239, 256, 279,
    325, 329,
];

pub static TRACE_STAT: [usize; 1] = [4];

pub static TRACE_LSTAT: [usize; 1] = [6];

pub static TRACE_FSTAT: [usize; 3] = [5, 262, 332];

pub static TRACE_STAT_LIKE: [usize; 5] = [4, 5, 6, 262, 332];

pub static TRACE_STATFS: [usize; 1] = [137];

pub static TRACE_FSTATFS: [usize; 1] = [138];

pub static TRACE_STATFS_LIKE: [usize; 3] = [136, 137, 138];

pub static TRACE_PURE: [usize; 8] = [39, 102, 104, 107, 108, 110, 111, 186];

pub static TRACE_CREDS: [usize; 19] = [
    102, 104, 105, 106, 107, 108, 113, 114, 115, 116, 117, 118, 119, 120, 122, 123, 125, 126, 157,
];

pub static TRACE_CLOCK: [usize; 8] = [96, 159, 164, 201, 227, 228, 229, 305];

macro_rules! syscall {
    ($name:literal $(,)?) => {
        ($name, [None, None, None, None, None, None])
    };
    ($name:literal, $arg0:ident $(,)?) => {
        ($name, [$arg0, None, None, None, None, None])
    };
    ($name:literal, $arg0:ident, $arg1:ident $(,)?) => {
        ($name, [$arg0, $arg1, None, None, None, None])
    };
    ($name:literal, $arg0:ident, $arg1:ident, $arg2:ident $(,)?) => {
        ($name, [$arg0, $arg1, $arg2, None, None, None])
    };
    ($name:literal, $arg0:ident, $arg1:ident, $arg2:ident, $arg3:ident $(,)?) => {
        ($name, [$arg0, $arg1, $arg2, $arg3, None, None])
    };
    ($name:literal, $arg0:ident, $arg1:ident, $arg2:ident, $arg3:ident, $arg4:ident $(,)?) => {
        ($name, [$arg0, $arg1, $arg2, $arg3, $arg4, None])
    };
    ($name:literal, $arg0:ident, $arg1:ident, $arg2:ident, $arg3:ident, $arg4:ident, $arg5:ident $(,)?) => {
        ($name, [$arg0, $arg1, $arg2, $arg3, $arg4, $arg5])
    };
}

const ADDR: Option<SystemCallArgumentType> = Some(SystemCallArgumentType::Address);
const INT: Option<SystemCallArgumentType> = Some(SystemCallArgumentType::Integer);
const STR: Option<SystemCallArgumentType> = Some(SystemCallArgumentType::String);

pub static SYSTEM_CALLS: [(&str, [Option<SystemCallArgumentType>; 6]); 335] = [
    syscall!("read", INT, STR, INT),
    syscall!("write", INT, STR, INT),
    syscall!("open", STR, INT, INT),
    syscall!("close", INT),
    syscall!("stat", STR, ADDR),
    syscall!("fstat", INT, ADDR),
    syscall!("lstat", STR, ADDR),
    syscall!("poll", ADDR, INT, INT),
    syscall!("lseek", INT, INT, INT),
    syscall!("mmap", ADDR, INT, INT, INT, INT, INT),
    syscall!("mprotect", ADDR, INT, INT),
    syscall!("munmap", ADDR, INT),
    syscall!("brk", ADDR),
    syscall!("rt_sigaction", INT, ADDR, ADDR),
    syscall!("rt_sigprocmask", INT, ADDR, ADDR, INT),
    syscall!("rt_sigreturn"),
    syscall!("ioctl", INT, INT, ADDR),
    syscall!("pread64", INT, STR, INT, INT),
    syscall!("pwrite64", INT, STR, INT, INT),
    syscall!("readv", INT, ADDR, INT),
    syscall!("writev", INT, ADDR, INT),
    syscall!("access", STR, INT),
    syscall!("pipe", INT, INT),
    syscall!("select", INT, ADDR, ADDR, ADDR, ADDR),
    syscall!("sched_yield", ADDR),
    syscall!("mremap", ADDR, INT, INT, INT, ADDR),
    syscall!("msync", ADDR, INT, INT),
    syscall!("mincore", ADDR, INT, ADDR),
    syscall!("madvise", ADDR, INT, INT),
    syscall!("shmget", INT, INT, INT),
    syscall!("shmat", INT, ADDR, INT),
    syscall!("shmctl", INT, INT, STR),
    syscall!("dup", INT),
    syscall!("dup2", INT, INT),
    syscall!("pause", ADDR),
    syscall!("nanosleep", ADDR, ADDR),
    syscall!("getitimer", INT, ADDR),
    syscall!("alarm", INT),
    syscall!("setitimer", INT, ADDR),
    syscall!("getpid", ADDR),
    syscall!("sendfile", INT, INT, ADDR, INT),
    syscall!("socket", INT, INT, INT),
    syscall!("connect", INT, ADDR, INT),
    syscall!("accept", INT, ADDR, ADDR),
    syscall!("sendto", INT, STR, INT, INT),
    syscall!("recvfrom", INT, STR, INT, INT, ADDR, ADDR),
    syscall!("sendmsg", INT, ADDR, INT),
    syscall!("recvmsg", INT, ADDR, INT),
    syscall!("shutdown", INT, INT),
    syscall!("bind", INT, ADDR, INT),
    syscall!("listen", INT, INT),
    syscall!("getsockname", INT, ADDR, ADDR),
    syscall!("getpeername", INT, ADDR, ADDR),
    syscall!("socketpair", INT, INT, INT, INT),
    syscall!("setsockopt", INT, INT, INT, ADDR, INT),
    syscall!("getsockopt", INT, INT, INT, ADDR, ADDR),
    syscall!("clone", ADDR, INT),
    syscall!("fork", ADDR),
    syscall!("vfork", ADDR),
    syscall!("execve", STR, STR, STR),
    syscall!("exit", INT),
    syscall!("wait4", INT, INT, INT, ADDR),
    syscall!("kill", INT, INT),
    syscall!("uname", ADDR),
    syscall!("semget", INT, INT, INT),
    syscall!("semop", INT, ADDR, INT),
    syscall!("semctl", INT, INT, INT),
    syscall!("shmdt", INT, ADDR, INT),
    syscall!("msgget", INT, INT),
    syscall!("msgsnd", INT, ADDR, INT, INT),
    syscall!("msgrcv", INT, ADDR, INT, INT, INT),
    syscall!("msgctl", INT, INT, ADDR),
    syscall!("fcntl", INT, INT),
    syscall!("flock", INT, INT),
    syscall!("fsync", INT),
    syscall!("fdatasync", INT),
    syscall!("truncate", STR, INT),
    syscall!("ftruncate", INT, INT),
    syscall!("getdents", INT, ADDR, INT),
    syscall!("getcwd", STR, INT),
    syscall!("chdir", STR),
    syscall!("fchdir", INT),
    syscall!("rename", STR, STR),
    syscall!("mkdir", STR, INT),
    syscall!("rmdir", STR),
    syscall!("creat", STR, INT),
    syscall!("link", STR, STR),
    syscall!("unlink", STR),
    syscall!("symlink", STR, STR),
    syscall!("readlink", STR, STR, INT),
    syscall!("chmod", STR, INT),
    syscall!("fchmod", INT, INT),
    syscall!("chown", STR, INT, INT),
    syscall!("fchown", INT, INT, INT),
    syscall!("lchown", STR, INT, INT),
    syscall!("umask", INT),
    syscall!("gettimeofday", ADDR, ADDR),
    syscall!("getrlimit", INT, ADDR),
    syscall!("getrusage", INT, ADDR),
    syscall!("sysinfo", ADDR),
    syscall!("times", ADDR),
    syscall!("ptrace", ADDR, INT, ADDR, ADDR),
    syscall!("getuid", ADDR),
    syscall!("syslog", INT, STR, INT),
    syscall!("getgid", ADDR),
    syscall!("setuid", INT),
    syscall!("setgid", INT),
    syscall!("geteuid", ADDR),
    syscall!("getegid", ADDR),
    syscall!("setpgid", INT, INT, INT),
    syscall!("getppid", ADDR),
    syscall!("getpgrp", ADDR),
    syscall!("setsid", ADDR),
    syscall!("setreuid", INT, INT),
    syscall!("setregid", INT, INT),
    syscall!("getgroups", INT, INT),
    syscall!("setgroups", INT, INT),
    syscall!("setresuid", INT, INT, INT),
    syscall!("getresuid", INT, INT, INT),
    syscall!("setresgid", INT, INT, INT),
    syscall!("getresgid", INT, INT, INT),
    syscall!("getpgid", INT),
    syscall!("setfsuid", INT),
    syscall!("setfsgid", INT),
    syscall!("getsid", INT),
    syscall!("capget", ADDR, ADDR),
    syscall!("capset", ADDR, ADDR),
    syscall!("rt_sigpending", ADDR),
    syscall!("rt_sigtimedwait", ADDR, ADDR, ADDR),
    syscall!("rt_sigqueueinfo", INT, INT, ADDR),
    syscall!("rt_sigsuspend", INT),
    syscall!("sigaltstack", ADDR, ADDR),
    syscall!("utime", STR, ADDR, INT),
    syscall!("mknod", STR, INT, INT),
    syscall!("uselib", ADDR),
    syscall!("personality", INT),
    syscall!("ustat", INT, ADDR),
    syscall!("statfs", STR, ADDR),
    syscall!("fstatfs", INT, ADDR),
    syscall!("sysfs", INT, STR),
    syscall!("getpriority", INT, INT),
    syscall!("setpriority", INT, INT, INT),
    syscall!("sched_setparam", INT, ADDR),
    syscall!("sched_getparam", INT, ADDR),
    syscall!("sched_setscheduler", INT, INT, ADDR),
    syscall!("sched_getscheduler", INT),
    syscall!("sched_get_priority_max", INT),
    syscall!("sched_get_priority_min", INT),
    syscall!("sched_rr_get_interval", INT, ADDR),
    syscall!("mlock", ADDR, INT),
    syscall!("munlock", ADDR, INT),
    syscall!("mlockall", INT),
    syscall!("munlockall", ADDR),
    syscall!("vhangup", ADDR),
    syscall!("modify_ldt", INT, ADDR, INT),
    syscall!("pivot_root", STR, STR),
    syscall!("_sysctl", ADDR),
    syscall!("prctl", INT, INT, INT, INT, INT),
    syscall!("arch_prctl", INT, ADDR),
    syscall!("adjtimex", STR),
    syscall!("setrlimit", INT, ADDR),
    syscall!("chroot", STR),
    syscall!("sync", INT),
    syscall!("acct", STR),
    syscall!("settimeofday", ADDR, ADDR),
    syscall!("mount", STR, STR, STR, INT, ADDR),
    syscall!("umount2", STR, INT),
    syscall!("swapon", STR, INT),
    syscall!("swapoff", STR),
    syscall!("reboot", INT, INT, INT, ADDR),
    syscall!("sethostname", STR, INT),
    syscall!("setdomainname", STR, INT),
    syscall!("iopl", INT),
    syscall!("ioperm", INT, INT, INT),
    syscall!("create_module", STR, INT),
    syscall!("init_module", ADDR, INT, STR),
    syscall!("delete_module", STR, INT),
    syscall!("get_kernel_syms", ADDR),
    syscall!("query_module", STR, INT, STR, INT, INT),
    syscall!("quotactl", INT, STR, INT, ADDR),
    syscall!("nfsservctl", INT, ADDR, ADDR),
    syscall!("getpmsg"),
    syscall!("putpmsg"),
    syscall!("afs_syscall"),
    syscall!("tuxcall"),
    syscall!("security"),
    syscall!("gettid", ADDR),
    syscall!("readahead", INT, INT, INT),
    syscall!("setxattr", STR, STR, ADDR, INT, INT),
    syscall!("lsetxattr", STR, STR, ADDR, INT, INT),
    syscall!("fsetxattr", INT, STR, ADDR, INT, INT),
    syscall!("getxattr", STR, STR, ADDR, INT),
    syscall!("lgetxattr", STR, STR, ADDR, INT),
    syscall!("fgetxattr", INT, STR, ADDR, INT),
    syscall!("listxattr", STR, STR, INT),
    syscall!("llistxattr", STR, STR, INT),
    syscall!("flistxattr", INT, STR, INT),
    syscall!("removexattr", STR, STR),
    syscall!("lremovexattr", STR, STR),
    syscall!("fremovexattr", INT, STR),
    syscall!("tkill", INT, INT),
    syscall!("time", INT),
    syscall!("futex", ADDR, INT, INT, ADDR, INT, INT),
    syscall!("sched_setaffinity", INT, INT, INT),
    syscall!("sched_getaffinity", INT, INT, INT),
    syscall!("set_thread_area", ADDR),
    syscall!("io_setup", INT, ADDR),
    syscall!("io_destroy", INT),
    syscall!("io_getevents", INT, INT, INT, ADDR, INT),
    syscall!("io_submit", INT, INT, ADDR),
    syscall!("io_cancel", INT, ADDR, ADDR),
    syscall!("get_thread_area", ADDR),
    syscall!("lookup_dcookie", INT, STR, INT),
    syscall!("epoll_create", INT),
    syscall!("epoll_ctl_old", INT, INT, INT, ADDR),
    syscall!("epoll_wait_old", INT, ADDR, INT, INT),
    syscall!("remap_file_pages", ADDR, INT, INT, INT, INT),
    syscall!("getdents64", INT, ADDR, INT),
    syscall!("set_tid_address", ADDR),
    syscall!("restart_syscall", ADDR),
    syscall!("semtimedop", INT, ADDR, INT),
    syscall!("fadvise64", INT, INT, INT, INT),
    syscall!("timer_create", INT, ADDR, INT),
    syscall!("timer_settime", INT, INT, ADDR, ADDR),
    syscall!("timer_gettime", INT, ADDR),
    syscall!("timer_getoverrun", INT),
    syscall!("timer_delete", INT),
    syscall!("clock_settime", INT, ADDR),
    syscall!("clock_gettime", INT, ADDR),
    syscall!("clock_getres", INT, ADDR),
    syscall!("clock_nanosleep", INT, INT, ADDR, ADDR),
    syscall!("exit_group", INT),
    syscall!("epoll_wait", INT, ADDR, INT, INT),
    syscall!("epoll_ctl", INT, INT, INT, ADDR),
    syscall!("tgkill", INT, INT, INT),
    syscall!("utimes", STR, ADDR),
    syscall!("vserver"),
    syscall!("mbind", ADDR, INT, INT, INT, INT, INT),
    syscall!("set_mempolicy", INT, INT, INT),
    syscall!("get_mempolicy", INT, INT, INT, ADDR, INT),
    syscall!("mq_open", STR, INT),
    syscall!("mq_unlink", STR),
    syscall!("mq_timedsend", INT, STR, INT, INT),
    syscall!("mq_timedreceive", INT, ADDR, INT, INT, ADDR),
    syscall!("mq_notify", INT, ADDR),
    syscall!("mq_getsetattr", INT, ADDR, ADDR),
    syscall!("kexec_load", INT, INT, ADDR, INT),
    syscall!("waitid", INT, INT, INT, INT),
    syscall!("add_key", STR, STR, ADDR, INT, INT),
    syscall!("request_key", STR, STR, STR, INT),
    syscall!("keyctl", INT),
    syscall!("ioprio_set", INT, INT),
    syscall!("ioprio_get", INT, INT),
    syscall!("inotify_init", ADDR),
    syscall!("inotify_add_watch", INT, STR, INT),
    syscall!("inotify_rm_watch", INT, INT),
    syscall!("migrate_pages", INT, INT, INT, INT),
    syscall!("openat", INT, STR, INT),
    syscall!("mkdirat", INT, STR, INT),
    syscall!("mknodat", INT, STR, INT, INT),
    syscall!("fchownat", INT, STR, INT, INT, INT),
    syscall!("futimesat", INT, STR, ADDR),
    syscall!("newfstatat", INT, STR, ADDR, INT),
    syscall!("unlinkat", INT, STR, INT),
    syscall!("renameat", INT, STR, INT, STR),
    syscall!("linkat", INT, STR, INT, STR, INT),
    syscall!("symlinkat", STR, INT, STR),
    syscall!("readlinkat", INT, STR, STR, INT),
    syscall!("fchmodat", INT, STR, INT, INT),
    syscall!("faccessat", INT, STR, INT, INT),
    syscall!("pselect6", INT, INT, INT, INT, ADDR, INT),
    syscall!("ppoll", INT, INT, ADDR, INT),
    syscall!("unshare", INT),
    syscall!("set_robust_list", ADDR, INT),
    syscall!("get_robust_list", INT, ADDR, INT),
    syscall!("splice", INT, INT, INT, INT, INT, INT),
    syscall!("tee", INT, INT, INT, INT),
    syscall!("sync_file_range", INT, INT, INT, INT),
    syscall!("vmsplice", INT, ADDR, INT, INT),
    syscall!("move_pages", INT, INT, ADDR, INT, INT, INT),
    syscall!("utimensat", INT, STR, ADDR, INT),
    syscall!("epoll_pwait", INT, ADDR, INT, INT, INT),
    syscall!("signalfd", INT, INT, INT),
    syscall!("timerfd_create", INT, INT),
    syscall!("eventfd", INT, INT),
    syscall!("fallocate", INT, INT, INT, INT),
    syscall!("timerfd_settime", INT, INT, ADDR),
    syscall!("timerfd_gettime", INT, ADDR),
    syscall!("accept4", INT, ADDR, INT),
    syscall!("signalfd4", INT, INT, INT),
    syscall!("eventfd2", INT, INT),
    syscall!("epoll_create1", INT),
    syscall!("dup3", INT, INT, INT),
    syscall!("pipe2", INT, INT),
    syscall!("inotify_init1", INT),
    syscall!("preadv", INT, ADDR, INT, INT),
    syscall!("pwritev", INT, ADDR, INT, INT),
    syscall!("rt_tgsigqueueinfo", INT, INT, INT),
    syscall!("perf_event_open", ADDR, INT, INT, INT, INT),
    syscall!("recvmmsg", INT, ADDR, INT, INT, ADDR),
    syscall!("fanotify_init", INT, INT),
    syscall!("fanotify_mark", INT, INT, INT, INT, STR),
    syscall!("prlimit64", INT, INT, ADDR, ADDR),
    syscall!("name_to_handle_at", INT, STR, ADDR, INT, INT),
    syscall!("open_by_handle_at", INT, ADDR, INT),
    syscall!("clock_adjtime", ADDR),
    syscall!("syncfs", INT),
    syscall!("sendmmsg", INT, ADDR, INT, INT),
    syscall!("setns", INT, INT),
    syscall!("getcpu", INT, INT, ADDR),
    syscall!("process_vm_readv", INT, ADDR, INT, ADDR, INT, INT),
    syscall!("process_vm_writev", INT, ADDR, INT, ADDR, INT, INT),
    syscall!("kcmp", INT, INT, INT, INT, INT),
    syscall!("finit_module", INT, STR, INT),
    syscall!("sched_setattr", INT, ADDR, INT),
    syscall!("sched_getattr", INT, ADDR, INT, INT),
    syscall!("renameat2", INT, STR, INT, STR),
    syscall!("seccomp", INT, INT, ADDR),
    syscall!("getrandom", STR, INT, INT),
    syscall!("memfd_create", STR, INT),
    syscall!("kexec_file_load", INT, INT, ADDR, INT),
    syscall!("bpf", INT, ADDR, INT),
    syscall!("execveat", INT, STR, STR, STR, INT),
    syscall!("userfaultfd", INT),
    syscall!("membarrier", INT, INT, INT),
    syscall!("mlock2", ADDR, INT, INT),
    syscall!("copy_file_range", INT, INT, INT, INT, INT, INT),
    syscall!("preadv2", INT, ADDR, INT, INT, INT),
    syscall!("pwritev2", INT, ADDR, INT, INT, INT),
    syscall!("pkey_mprotect", ADDR, INT, INT, INT),
    syscall!("pkey_alloc", INT, INT),
    syscall!("pkey_free", INT),
    syscall!("statx", INT, STR, INT, INT, STR),
    syscall!("io_pgetevents"),
    syscall!("rseq"),
];
