#[derive(Copy, Clone)]
pub enum SystemCallArgumentType {
    // Integer can be used to represent int, fd and size_t
    Integer,
    // String can be used to represent *buf
    String,
    // Address can be used to represent *statbuf
    Address,
    // None can be used if a syscall has fewer than 6 arguments
    None,
}

pub static Register: [&str; 6] = ["rdi", "rsi", "rdx", "r10", "r8", "r9"];

pub static SYSTEM_CALLS: [(&str, SystemCallArgumentType, SystemCallArgumentType, SystemCallArgumentType, SystemCallArgumentType, SystemCallArgumentType, SystemCallArgumentType); 3] = [
    ("read", SystemCallArgumentType::Integer, SystemCallArgumentType::String, SystemCallArgumentType::Integer, SystemCallArgumentType::None, SystemCallArgumentType::None, SystemCallArgumentType::None),
    ("write", SystemCallArgumentType::Integer, SystemCallArgumentType::String, SystemCallArgumentType::Integer, SystemCallArgumentType::None, SystemCallArgumentType::None, SystemCallArgumentType::None),
    ("open", SystemCallArgumentType::String, SystemCallArgumentType::Integer, SystemCallArgumentType::Integer, SystemCallArgumentType::None, SystemCallArgumentType::None, SystemCallArgumentType::None),
    // ("close", vec![]),
    // ("stat",vec![SystemCallArgumentType::String, SystemCallArgumentType::String]),
    // ("fstat",vec![SystemCallArgumentType::Integer, SystemCallArgumentType::String]),
    // ("lstat",vec![SystemCallArgumentType::String, SystemCallArgumentType::String]),
    // ("poll",vec![]),
    // ("lseek",vec![]),
    // ("mmap",vec![]),
    // ("mprotect",vec![]),
    // ("munmap",vec![]),
    // ("brk",vec![]),
    // ("rt_sigaction",vec![]),
    // ("rt_sigprocmask",vec![]),
    // ("rt_sigreturn",vec![]),
    // ("ioctl",vec![]),
    // ("pread64",vec![]),
    // ("pwrite64",vec![]),
    // ("readv",vec![]),
    // ("writev",vec![]),
    // ("access",vec![]),
    // ("pipe",vec![]),
    // ("select",vec![]),
    // ("sched_yield",vec![]),
    // ("mremap",vec![]),
    // ("msync",vec![]),
    // ("mincore",vec![]),
    // ("madvise",vec![]),
    // ("shmget",vec![]),
    // ("shmat",vec![]),
    // ("shmctl",vec![]),
    // ("dup",vec![]),
    // ("dup2",vec![]),
    // ("pause",vec![]),
    // ("nanosleep",vec![]),
    // ("getitimer",vec![]),
    // ("alarm",vec![]),
    // ("setitimer",vec![]),
    // ("getpid",vec![]),
    // ("sendfile",vec![]),
    // ("socket",vec![]),
    // ("connect",vec![]),
    // ("accept",vec![]),
    // ("sendto",vec![]),
    // ("recvfrom",vec![]),
    // ("sendmsg",vec![]),
    // ("recvmsg",vec![]),
    // ("shutdown",vec![]),
    // ("bind",vec![]),
    // ("listen",vec![]),
    // ("getsockname",vec![]),
    // ("getpeername",vec![]),
    // ("socketpair",vec![]),
    // ("setsockopt",vec![]),
    // ("getsockopt",vec![]),
    // ("clone",vec![]),
    // ("fork",vec![]),
    // ("vfork",vec![]),
    // ("execve",vec![]),
    // ("exit",vec![]),
    // ("wait4",vec![]),
    // ("kill",vec![]),
    // ("uname",vec![]),
    // ("semget",vec![]),
    // ("semop",vec![]),
    // ("semctl",vec![]),
    // ("shmdt",vec![]),
    // ("msgget",vec![]),
    // ("msgsnd",vec![]),
    // ("msgrcv",vec![]),
    // ("msgctl",vec![]),
    // ("fcntl",vec![]),
    // ("flock",vec![]),
    // ("fsync",vec![]),
    // ("fdatasync",vec![]),
    // ("truncate",vec![]),
    // ("ftruncate",vec![]),
    // ("getdents",vec![]),
    // ("getcwd",vec![]),
    // ("chdir",vec![]),
    // ("fchdir",vec![]),
    // ("rename",vec![]),
    // ("mkdir",vec![]),
    // ("rmdir",vec![]),
    // ("creat",vec![]),
    // ("link",vec![]),
    // ("unlink",vec![]),
    // ("symlink",vec![]),
    // ("readlink",vec![]),
    // ("chmod",vec![]),
    // ("fchmod",vec![]),
    // ("chown",vec![]),
    // ("fchown",vec![]),
    // ("lchown",vec![]),
    // ("umask",vec![]),
    // ("gettimeofday",vec![]),
    // ("getrlimit",vec![]),
    // ("getrusage",vec![]),
    // ("sysinfo",vec![]),
    // ("times",vec![]),
    // ("ptrace",vec![]),
    // ("getuid",vec![]),
    // ("syslog",vec![]),
    // ("getgid",vec![]),
    // ("setuid",vec![]),
    // ("setgid",vec![]),
    // ("geteuid",vec![]),
    // ("getegid",vec![]),
    // ("setpgid",vec![]),
    // ("getppid",vec![]),
    // ("getpgrp",vec![]),
    // ("setsid",vec![]),
    // ("setreuid",vec![]),
    // ("setregid",vec![]),
    // ("getgroups",vec![]),
    // ("setgroups",vec![]),
    // ("setresuid",vec![]),
    // ("getresuid",vec![]),
    // ("setresgid",vec![]),
    // ("getresgid",vec![]),
    // ("getpgid",vec![]),
    // ("setfsuid",vec![]),
    // ("setfsgid",vec![]),
    // ("getsid",vec![]),
    // ("capget",vec![]),
    // ("capset",vec![]),
    // ("rt_sigpending",vec![]),
    // ("rt_sigtimedwait",vec![]),
    // ("rt_sigqueueinfo",vec![]),
    // ("rt_sigsuspend",vec![]),
    // ("sigaltstack",vec![]),
    // ("utime",vec![]),
    // ("mknod",vec![]),
    // ("uselib",vec![]),
    // ("personality",vec![]),
    // ("ustat",vec![]),
    // ("statfs",vec![]),
    // ("fstatfs",vec![]),
    // ("sysfs",vec![]),
    // ("getpriority",vec![]),
    // ("setpriority",vec![]),
    // ("sched_setparam",vec![]),
    // ("sched_getparam",vec![]),
    // ("sched_setscheduler",vec![]),
    // ("sched_getscheduler",vec![]),
    // ("sched_get_priority_max",vec![]),
    // ("sched_get_priority_min",vec![]),
    // ("sched_rr_get_interval",vec![]),
    // ("mlock",vec![]),
    // ("munlock",vec![]),
    // ("mlockall",vec![]),
    // ("munlockall",vec![]),
    // ("vhangup",vec![]),
    // ("modify_ldt",vec![]),
    // ("pivot_root",vec![]),
    // ("_sysctl",vec![]),
    // ("prctl",vec![]),
    // ("arch_prctl",vec![]),
    // ("adjtimex",vec![]),
    // ("setrlimit",vec![]),
    // ("chroot",vec![]),
    // ("sync",vec![]),
    // ("acct",vec![]),
    // ("settimeofday",vec![]),
    // ("mount",vec![]),
    // ("umount2",vec![]),
    // ("swapon",vec![]),
    // ("swapoff",vec![]),
    // ("reboot",vec![]),
    // ("sethostname",vec![]),
    // ("setdomainname",vec![]),
    // ("iopl",vec![]),
    // ("ioperm",vec![]),
    // ("create_module",vec![]),
    // ("init_module",vec![]),
    // ("delete_module",vec![]),
    // ("get_kernel_syms",vec![]),
    // ("query_module",vec![]),
    // ("quotactl",vec![]),
    // ("nfsservctl",vec![]),
    // ("getpmsg",vec![]),
    // ("putpmsg",vec![]),
    // ("afs_syscall",vec![]),
    // ("tuxcall",vec![]),
    // ("security",vec![]),
    // ("gettid",vec![]),
    // ("readahead",vec![]),
    // ("setxattr",vec![]),
    // ("lsetxattr",vec![]),
    // ("fsetxattr",vec![]),
    // ("getxattr",vec![]),
    // ("lgetxattr",vec![]),
    // ("fgetxattr",vec![]),
    // ("listxattr",vec![]),
    // ("llistxattr",vec![]),
    // ("flistxattr",vec![]),
    // ("removexattr",vec![]),
    // ("lremovexattr",vec![]),
    // ("fremovexattr",vec![]),
    // ("tkill",vec![]),
    // ("time",vec![]),
    // ("futex",vec![]),
    // ("sched_setaffinity",vec![]),
    // ("sched_getaffinity",vec![]),
    // ("set_thread_area",vec![]),
    // ("io_setup",vec![]),
    // ("io_destroy",vec![]),
    // ("io_getevents",vec![]),
    // ("io_submit",vec![]),
    // ("io_cancel",vec![]),
    // ("get_thread_area",vec![]),
    // ("lookup_dcookie",vec![]),
    // ("epoll_create",vec![]),
    // ("epoll_ctl_old",vec![]),
    // ("epoll_wait_old",vec![]),
    // ("remap_file_pages",vec![]),
    // ("getdents64",vec![]),
    // ("set_tid_address",vec![]),
    // ("restart_syscall",vec![]),
    // ("semtimedop",vec![]),
    // ("fadvise64",vec![]),
    // ("timer_create",vec![]),
    // ("timer_settime",vec![]),
    // ("timer_gettime",vec![]),
    // ("timer_getoverrun",vec![]),
    // ("timer_delete",vec![]),
    // ("clock_settime",vec![]),
    // ("clock_gettime",vec![]),
    // ("clock_getres",vec![]),
    // ("clock_nanosleep",vec![]),
    // ("exit_group",vec![]),
    // ("epoll_wait",vec![]),
    // ("epoll_ctl",vec![]),
    // ("tgkill",vec![]),
    // ("utimes",vec![]),
    // ("vserver",vec![]),
    // ("mbind",vec![]),
    // ("set_mempolicy",vec![]),
    // ("get_mempolicy",vec![]),
    // ("mq_open",vec![]),
    // ("mq_unlink",vec![]),
    // ("mq_timedsend",vec![]),
    // ("mq_timedreceive",vec![]),
    // ("mq_notify",vec![]),
    // ("mq_getsetattr",vec![]),
    // ("kexec_load",vec![]),
    // ("waitid",vec![]),
    // ("add_key",vec![]),
    // ("request_key",vec![]),
    // ("keyctl",vec![]),
    // ("ioprio_set",vec![]),
    // ("ioprio_get",vec![]),
    // ("inotify_init",vec![]),
    // ("inotify_add_watch",vec![]),
    // ("inotify_rm_watch",vec![]),
    // ("migrate_pages",vec![]),
    // ("openat",vec![]),
    // ("mkdirat",vec![]),
    // ("mknodat",vec![]),
    // ("fchownat",vec![]),
    // ("futimesat",vec![]),
    // ("newfstatat",vec![]),
    // ("unlinkat",vec![]),
    // ("renameat",vec![]),
    // ("linkat",vec![]),
    // ("symlinkat",vec![]),
    // ("readlinkat",vec![]),
    // ("fchmodat",vec![]),
    // ("faccessat",vec![]),
    // ("pselect6",vec![]),
    // ("ppoll",vec![]),
    // ("unshare",vec![]),
    // ("set_robust_list",vec![]),
    // ("get_robust_list",vec![]),
    // ("splice",vec![]),
    // ("tee",vec![]),
    // ("sync_file_range",vec![]),
    // ("vmsplice",vec![]),
    // ("move_pages",vec![]),
    // ("utimensat",vec![]),
    // ("epoll_pwait",vec![]),
    // ("signalfd",vec![]),
    // ("timerfd_create",vec![]),
    // ("eventfd",vec![]),
    // ("fallocate",vec![]),
    // ("timerfd_settime",vec![]),
    // ("timerfd_gettime",vec![]),
    // ("accept4",vec![]),
    // ("signalfd4",vec![]),
    // ("eventfd2",vec![]),
    // ("epoll_create1",vec![]),
    // ("dup3",vec![]),
    // ("pipe2",vec![]),
    // ("inotify_init1",vec![]),
    // ("preadv",vec![]),
    // ("pwritev",vec![]),
    // ("rt_tgsigqueueinfo",vec![]),
    // ("perf_event_open",vec![]),
    // ("recvmmsg",vec![]),
    // ("fanotify_init",vec![]),
    // ("fanotify_mark",vec![]),
    // ("prlimit64",vec![]),
    // ("name_to_handle_at",vec![]),
    // ("open_by_handle_at",vec![]),
    // ("clock_adjtime",vec![]),
    // ("syncfs",vec![]),
    // ("sendmmsg",vec![]),
    // ("setns",vec![]),
    // ("getcpu",vec![]),
    // ("process_vm_readv",vec![]),
    // ("process_vm_writev",vec![]),
    // ("kcmp",vec![]),
    // ("finit_module",vec![]),
    // ("sched_setattr",vec![]),
    // ("sched_getattr",vec![]),
    // ("renameat2",vec![]),
    // ("seccomp",vec![]),
    // ("getrandom",vec![]),
    // ("memfd_create",vec![]),
    // ("kexec_file_load",vec![]),
    // ("bpf",vec![]),
    // ("execveat",vec![]),
    // ("userfaultfd",vec![]),
    // ("membarrier",vec![]),
    // ("mlock2",vec![]),
    // ("copy_file_range",vec![]),
    // ("preadv2",vec![]),
    // ("pwritev2",vec![]),
    // ("pkey_mprotect",vec![]),
    // ("pkey_alloc",vec![]),
    // ("pkey_free",vec![]),
    // ("statx",vec![]),
    // ("io_pgetevents",vec![]),
    // ("rseq",vec![]),
];

pub static SYSTEM_CALL_NAMES: [&str; 335] = [
    "read",
    "write",
    "open",
    "close",
    "stat",
    "fstat",
    "lstat",
    "poll",
    "lseek",
    "mmap",
    "mprotect",
    "munmap",
    "brk",
    "rt_sigaction",
    "rt_sigprocmask",
    "rt_sigreturn",
    "ioctl",
    "pread64",
    "pwrite64",
    "readv",
    "writev",
    "access",
    "pipe",
    "select",
    "sched_yield",
    "mremap",
    "msync",
    "mincore",
    "madvise",
    "shmget",
    "shmat",
    "shmctl",
    "dup",
    "dup2",
    "pause",
    "nanosleep",
    "getitimer",
    "alarm",
    "setitimer",
    "getpid",
    "sendfile",
    "socket",
    "connect",
    "accept",
    "sendto",
    "recvfrom",
    "sendmsg",
    "recvmsg",
    "shutdown",
    "bind",
    "listen",
    "getsockname",
    "getpeername",
    "socketpair",
    "setsockopt",
    "getsockopt",
    "clone",
    "fork",
    "vfork",
    "execve",
    "exit",
    "wait4",
    "kill",
    "uname",
    "semget",
    "semop",
    "semctl",
    "shmdt",
    "msgget",
    "msgsnd",
    "msgrcv",
    "msgctl",
    "fcntl",
    "flock",
    "fsync",
    "fdatasync",
    "truncate",
    "ftruncate",
    "getdents",
    "getcwd",
    "chdir",
    "fchdir",
    "rename",
    "mkdir",
    "rmdir",
    "creat",
    "link",
    "unlink",
    "symlink",
    "readlink",
    "chmod",
    "fchmod",
    "chown",
    "fchown",
    "lchown",
    "umask",
    "gettimeofday",
    "getrlimit",
    "getrusage",
    "sysinfo",
    "times",
    "ptrace",
    "getuid",
    "syslog",
    "getgid",
    "setuid",
    "setgid",
    "geteuid",
    "getegid",
    "setpgid",
    "getppid",
    "getpgrp",
    "setsid",
    "setreuid",
    "setregid",
    "getgroups",
    "setgroups",
    "setresuid",
    "getresuid",
    "setresgid",
    "getresgid",
    "getpgid",
    "setfsuid",
    "setfsgid",
    "getsid",
    "capget",
    "capset",
    "rt_sigpending",
    "rt_sigtimedwait",
    "rt_sigqueueinfo",
    "rt_sigsuspend",
    "sigaltstack",
    "utime",
    "mknod",
    "uselib",
    "personality",
    "ustat",
    "statfs",
    "fstatfs",
    "sysfs",
    "getpriority",
    "setpriority",
    "sched_setparam",
    "sched_getparam",
    "sched_setscheduler",
    "sched_getscheduler",
    "sched_get_priority_max",
    "sched_get_priority_min",
    "sched_rr_get_interval",
    "mlock",
    "munlock",
    "mlockall",
    "munlockall",
    "vhangup",
    "modify_ldt",
    "pivot_root",
    "_sysctl",
    "prctl",
    "arch_prctl",
    "adjtimex",
    "setrlimit",
    "chroot",
    "sync",
    "acct",
    "settimeofday",
    "mount",
    "umount2",
    "swapon",
    "swapoff",
    "reboot",
    "sethostname",
    "setdomainname",
    "iopl",
    "ioperm",
    "create_module",
    "init_module",
    "delete_module",
    "get_kernel_syms",
    "query_module",
    "quotactl",
    "nfsservctl",
    "getpmsg",
    "putpmsg",
    "afs_syscall",
    "tuxcall",
    "security",
    "gettid",
    "readahead",
    "setxattr",
    "lsetxattr",
    "fsetxattr",
    "getxattr",
    "lgetxattr",
    "fgetxattr",
    "listxattr",
    "llistxattr",
    "flistxattr",
    "removexattr",
    "lremovexattr",
    "fremovexattr",
    "tkill",
    "time",
    "futex",
    "sched_setaffinity",
    "sched_getaffinity",
    "set_thread_area",
    "io_setup",
    "io_destroy",
    "io_getevents",
    "io_submit",
    "io_cancel",
    "get_thread_area",
    "lookup_dcookie",
    "epoll_create",
    "epoll_ctl_old",
    "epoll_wait_old",
    "remap_file_pages",
    "getdents64",
    "set_tid_address",
    "restart_syscall",
    "semtimedop",
    "fadvise64",
    "timer_create",
    "timer_settime",
    "timer_gettime",
    "timer_getoverrun",
    "timer_delete",
    "clock_settime",
    "clock_gettime",
    "clock_getres",
    "clock_nanosleep",
    "exit_group",
    "epoll_wait",
    "epoll_ctl",
    "tgkill",
    "utimes",
    "vserver",
    "mbind",
    "set_mempolicy",
    "get_mempolicy",
    "mq_open",
    "mq_unlink",
    "mq_timedsend",
    "mq_timedreceive",
    "mq_notify",
    "mq_getsetattr",
    "kexec_load",
    "waitid",
    "add_key",
    "request_key",
    "keyctl",
    "ioprio_set",
    "ioprio_get",
    "inotify_init",
    "inotify_add_watch",
    "inotify_rm_watch",
    "migrate_pages",
    "openat",
    "mkdirat",
    "mknodat",
    "fchownat",
    "futimesat",
    "newfstatat",
    "unlinkat",
    "renameat",
    "linkat",
    "symlinkat",
    "readlinkat",
    "fchmodat",
    "faccessat",
    "pselect6",
    "ppoll",
    "unshare",
    "set_robust_list",
    "get_robust_list",
    "splice",
    "tee",
    "sync_file_range",
    "vmsplice",
    "move_pages",
    "utimensat",
    "epoll_pwait",
    "signalfd",
    "timerfd_create",
    "eventfd",
    "fallocate",
    "timerfd_settime",
    "timerfd_gettime",
    "accept4",
    "signalfd4",
    "eventfd2",
    "epoll_create1",
    "dup3",
    "pipe2",
    "inotify_init1",
    "preadv",
    "pwritev",
    "rt_tgsigqueueinfo",
    "perf_event_open",
    "recvmmsg",
    "fanotify_init",
    "fanotify_mark",
    "prlimit64",
    "name_to_handle_at",
    "open_by_handle_at",
    "clock_adjtime",
    "syncfs",
    "sendmmsg",
    "setns",
    "getcpu",
    "process_vm_readv",
    "process_vm_writev",
    "kcmp",
    "finit_module",
    "sched_setattr",
    "sched_getattr",
    "renameat2",
    "seccomp",
    "getrandom",
    "memfd_create",
    "kexec_file_load",
    "bpf",
    "execveat",
    "userfaultfd",
    "membarrier",
    "mlock2",
    "copy_file_range",
    "preadv2",
    "pwritev2",
    "pkey_mprotect",
    "pkey_alloc",
    "pkey_free",
    "statx",
    "io_pgetevents",
    "rseq"
];